mv delivery/apples.txt fruit
mv delivery/bison_burgers.txt meat
mv delivery/brie.txt dairy
mv delivery/broccoli.txt veggies
mv delivery/carrot_cake.txt dessert
mv delivery/eggo_waffles.txt freezer
mv delivery/fage_yogurt.txt dairy
mv delivery/fig_bars.txt snax
mv delivery/flourless_cake dessert
mv delivery/garlic.txt veggies
mv delivery/goldfish.txt snax
mv delivery/grapples.txt fruit
mv delivery/hotdogs.txt meat
mv delivery/icecream.txt freezer
mv delivery/lamb_ribs.txt meat